
Create table MY_SCHEMA.TB_SAMPLE
(
    NR_SEQU_SAMPLE NUMBER(10) NOT NULL,
    DH_INCL DATE NOT NULL,
    NM_SAMPLE VARCHAR2(256) NULL
)
TABLESPACE TS_01;

CREATE UNIQUE INDEX MY_SCHEMA.PK_SAMPLE ON MY_SCHEMA.TB_SAMPLE
(NR_SEQU_SAMPLE  ASC)
	TABLESPACE TS_01;

ALTER TABLE MY_SCHEMA.TB_SAMPLE
	ADD CONSTRAINT  PK_SAMPLE PRIMARY KEY (NR_SEQU_SAMPLE);

GRANT SELECT, DELETE, INSERT, UPDATE ON MY_SCHEMA.TB_SAMPLE TO ADMIN;





